In [1]:
import kagglehub
path_1 = kagglehub.dataset_download("naiyakhalid/flood-prediction-dataset")
print('_'*60)
import os
import pandas as pd
if path_1:
  print(f"Path for data : {os.listdir(path_1)}")
else:
  print("file path is not found")

filepath = os.path.join(path_1,'flood.csv')

df_1 = pd.read_csv(filepath)
df_1.head()

Downloading to /root/.cache/kagglehub/datasets/naiyakhalid/flood-prediction-dataset/2.archive...

100%|██████████| 28.6M/28.6M [00:00<00:00, 80.9MB/s]

Extracting files...

____________________________________________________________
Path for data : ['sample_submission.csv', 'flood.csv', 'train.csv', 'test.csv']

,MonsoonIntensity,TopographyDrainage,RiverManagement,Deforestation,Urbanization,ClimateChange,DamsQuality,Siltation,AgriculturalPractices,Encroachments,...,DrainageSystems,CoastalVulnerability,Landslides,Watersheds,DeterioratingInfrastructure,PopulationScore,WetlandLoss,InadequatePlanning,PoliticalFactors,FloodProbability
0,3,8,6,6,4,4,6,2,3,2,...,10,7,4,2,3,4,3,2,6,0.450
1,8,4,5,7,7,9,1,5,5,4,...,9,2,6,2,1,1,9,1,3,0.475
2,3,10,4,1,7,5,4,7,4,9,...,7,4,4,8,6,1,8,3,6,0.515
3,4,4,2,7,3,4,1,4,6,4,...,4,2,6,6,8,8,6,6,10,0.520
4,3,7,5,2,5,8,5,2,7,5,...,7,6,5,3,3,4,4,3,4,0.475

In [2]:
import kagglehub

# Download latest version
path_2 = kagglehub.dataset_download("jsphyg/weather-dataset-rattle-package")

import os
import pandas as pd
if path_2:
  print(f"Path for data : {os.listdir(path_2)}")
else:
  print("file path is not found")

filepath = os.path.join(path_2,'weatherAUS.csv')

df_2 = pd.read_csv(filepath)
df_2.head()

Downloading to /root/.cache/kagglehub/datasets/jsphyg/weather-dataset-rattle-package/2.archive...

100%|██████████| 3.83M/3.83M [00:00<00:00, 71.9MB/s]

Extracting files...

Path for data : ['weatherAUS.csv']

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No

**Working on Flood Dataset**


---

In [4]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 21 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   MonsoonIntensity                 50000 non-null  int64
 1   TopographyDrainage               50000 non-null  int64
 2   RiverManagement                  50000 non-null  int64
 3   Deforestation                    50000 non-null  int64
 4   Urbanization                     50000 non-null  int64
 5   ClimateChange                    50000 non-null  int64
 6   DamsQuality                      50000 non-null  int64
 7   Siltation                        50000 non-null  int64
 8   AgriculturalPractices            50000 non-null  int64
 9   Encroachments                    50000 non-null  int64
 10  IneffectiveDisasterPreparedness  50000 non-null  int64
 11  DrainageSystems                  50000 non-null  int64
 12  CoastalVulnerability             50000 non-null  int64
 13  Landslides                       50000 non-null  int64
 14  Watersheds                       50000 non-null  int64
 15  DeterioratingInfrastructure      50000 non-null  int64
 16  PopulationScore                  50000 non-null  int64
 17  WetlandLoss                      50000 non-null  int64
 18  InadequatePlanning               50000 non-null  int64
 19  PoliticalFactors                 50000 non-null  int64
 20  FloodProbability                 50000 non-null  float64
dtypes: float64(1), int64(20)
memory usage: 8.0 MB

In [5]:
print(f"Missing Values : \n{df_1.isnull().sum()}")
print('_'*80)
print(f"Duplicate Values : \n{df_1.duplicated().sum()}")

Missing Values :
MonsoonIntensity                   0
TopographyDrainage                 0
RiverManagement                    0
Deforestation                      0
Urbanization                       0
ClimateChange                      0
DamsQuality                        0
Siltation                          0
AgriculturalPractices              0
Encroachments                      0
IneffectiveDisasterPreparedness    0
DrainageSystems                    0
CoastalVulnerability               0
Landslides                         0
Watersheds                         0
DeterioratingInfrastructure        0
PopulationScore                    0
WetlandLoss                        0
InadequatePlanning                 0
PoliticalFactors                   0
FloodProbability                   0
dtype: int64
________________________________________________________________________________
Duplicate Values :
0

In [6]:
df_1['Flood'] = df_1['FloodProbability'].apply(lambda x: 1 if x > 0.5 else 0)
print(df_1[['FloodProbability','Flood']].head(10))
df_1 = df_1.drop(columns = ['FloodProbability'],axis = 1)

   FloodProbability  Flood
0             0.450      0
1             0.475      0
2             0.515      1
3             0.520      1
4             0.475      0
5             0.470      0
6             0.570      1
7             0.585      1
8             0.580      1
9             0.555      1

**Build a small model for feature selection**

In [7]:
from sklearn.ensemble import RandomForestClassifier
X_train = df_1.drop(columns = ['Flood'])
y_train = df_1['Flood']
model = RandomForestClassifier(random_state=42)
model.fit(X_train,y_train)

importances = pd.Series(model.feature_importances_,index = X_train.columns)
importance = importances.sort_values(ascending = False)
importance

Watersheds                         0.051971
TopographyDrainage                 0.051259
DeterioratingInfrastructure        0.051147
IneffectiveDisasterPreparedness    0.050986
DamsQuality                        0.050750
Siltation                          0.050310
Landslides                         0.050156
MonsoonIntensity                   0.050151
AgriculturalPractices              0.049995
Urbanization                       0.049876
PopulationScore                    0.049823
CoastalVulnerability               0.049697
DrainageSystems                    0.049688
ClimateChange                      0.049495
Deforestation                      0.049460
PoliticalFactors                   0.049271
WetlandLoss                        0.049224
RiverManagement                    0.049159
Encroachments                      0.048791
InadequatePlanning                 0.048791
dtype: float64

In [8]:
df_1 = df_1.drop(columns = ["InadequatePlanning","PoliticalFactors","PopulationScore","AgriculturalPractices"])

In [9]:
df_1["rain_drainage"] = df_1['MonsoonIntensity']*df_1['DrainageSystems']
df_1["river_risk"] = df_1['RiverManagement']*df_1['Watersheds']
df_1['urban_drainage'] = df_1['Urbanization']*df_1['DrainageSystems']
df_1['forest_risk'] = df_1['Deforestation']*df_1['Landslides']

In [10]:
from xgboost import XGBClassifier
X_train = df_1.drop(columns = ['Flood'])
y_train = df_1['Flood']
xgb_model = XGBClassifier(random_state=42)
xgb_model.fit(X_train,y_train)

importances = pd.Series(xgb_model.feature_importances_,index = X_train.columns)
importance = importances.sort_values(ascending = False)
importance

forest_risk                        0.079762
river_risk                         0.078245
IneffectiveDisasterPreparedness    0.067422
TopographyDrainage                 0.064900
urban_drainage                     0.062743
rain_drainage                      0.062509
DeterioratingInfrastructure        0.062228
DamsQuality                        0.060591
WetlandLoss                        0.059492
CoastalVulnerability               0.059366
Siltation                          0.059156
ClimateChange                      0.057228
Encroachments                      0.053903
MonsoonIntensity                   0.039747
Urbanization                       0.036348
Watersheds                         0.022949
Deforestation                      0.020974
Landslides                         0.020606
RiverManagement                    0.018751
DrainageSystems                    0.013081
dtype: float32

In [11]:
df_1 = df_1.drop(columns = ['RiverManagement','Urbanization','DrainageSystems','Landslides','MonsoonIntensity','Watersheds','RiverManagement','Deforestation'])

In [12]:
from xgboost import XGBClassifier
X_train = df_1.drop(columns = ['Flood'])
y_train = df_1['Flood']
xgb_model = XGBClassifier(random_state=42)
xgb_model.fit(X_train,y_train)

importances = pd.Series(xgb_model.feature_importances_,index = X_train.columns)
importance = importances.sort_values(ascending = False)
importance

river_risk                         0.089793
IneffectiveDisasterPreparedness    0.084151
DeterioratingInfrastructure        0.082987
forest_risk                        0.080725
DamsQuality                        0.079072
ClimateChange                      0.077130
Siltation                          0.076673
TopographyDrainage                 0.075639
WetlandLoss                        0.074734
Encroachments                      0.072721
CoastalVulnerability               0.071320
rain_drainage                      0.067870
urban_drainage                     0.067184
dtype: float32

In [13]:
selected_columns = df_1.columns
print(f"Selected Columns are : {selected_columns}")

Selected Columns are : Index(['TopographyDrainage', 'ClimateChange', 'DamsQuality', 'Siltation',
       'Encroachments', 'IneffectiveDisasterPreparedness',
       'CoastalVulnerability', 'DeterioratingInfrastructure', 'WetlandLoss',
       'Flood', 'rain_drainage', 'river_risk', 'urban_drainage',
       'forest_risk'],
      dtype='object')

**Working on Weather Dataset**


---

In [14]:
# Handling Missing values
num_cols = df_2.select_dtypes(include = ['int64','float64'])
cat_cols = df_2.select_dtypes(include = ['object'])
for col in num_cols:
  df_2[col].fillna(df_2[col].mean(),inplace = True)
for col in cat_cols:
  df_2[col].fillna(df_2[col].mode()[0],inplace = True)

/tmp/ipykernel_6926/3885012000.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_2[col].fillna(df_2[col].mean(),inplace = True)
/tmp/ipykernel_6926/3885012000.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_2[col].fillna(df_2[col].mode()[0],inplace = True)

In [15]:
df_2['Date'] = pd.to_datetime(df_2['Date'])

In [16]:
print(f"Missing Values : {df_2.isnull().sum()}")

print(f"Dupliacted Value : {df_2.duplicated().sum()}")

Missing Values : Date             0
Location         0
MinTemp          0
MaxTemp          0
Rainfall         0
Evaporation      0
Sunshine         0
WindGustDir      0
WindGustSpeed    0
WindDir9am       0
WindDir3pm       0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud9am         0
Cloud3pm         0
Temp9am          0
Temp3pm          0
RainToday        0
RainTomorrow     0
dtype: int64
Dupliacted Value : 0

In [17]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145460 entries, 0 to 145459
Data columns (total 23 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           145460 non-null  datetime64[ns]
 1   Location       145460 non-null  object
 2   MinTemp        145460 non-null  float64
 3   MaxTemp        145460 non-null  float64
 4   Rainfall       145460 non-null  float64
 5   Evaporation    145460 non-null  float64
 6   Sunshine       145460 non-null  float64
 7   WindGustDir    145460 non-null  object
 8   WindGustSpeed  145460 non-null  float64
 9   WindDir9am     145460 non-null  object
 10  WindDir3pm     145460 non-null  object
 11  WindSpeed9am   145460 non-null  float64
 12  WindSpeed3pm   145460 non-null  float64
 13  Humidity9am    145460 non-null  float64
 14  Humidity3pm    145460 non-null  float64
 15  Pressure9am    145460 non-null  float64
 16  Pressure3pm    145460 non-null  float64
 17  Cloud9am       145460 non-null  float64
 18  Cloud3pm       145460 non-null  float64
 19  Temp9am        145460 non-null  float64
 20  Temp3pm        145460 non-null  float64
 21  RainToday      145460 non-null  object
 22  RainTomorrow   145460 non-null  object
dtypes: datetime64[ns](1), float64(16), object(6)
memory usage: 25.5+ MB

In [18]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for col in cat_cols:
  df_2[col] = le.fit_transform(df_2[col])
df_2.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,396,2,13.4,22.9,0.6,5.468232,7.611178,13,44.0,13,...,71.0,22.0,1007.7,1007.1,8.000000,4.50993,16.9,21.8,0,0
1,397,2,7.4,25.1,0.0,5.468232,7.611178,14,44.0,6,...,44.0,25.0,1010.6,1007.8,4.447461,4.50993,17.2,24.3,0,0
2,398,2,12.9,25.7,0.0,5.468232,7.611178,15,46.0,13,...,38.0,30.0,1007.6,1008.7,4.447461,2.00000,21.0,23.2,0,0
3,399,2,9.2,28.0,0.0,5.468232,7.611178,4,24.0,9,...,45.0,16.0,1017.6,1012.8,4.447461,4.50993,18.1,26.5,0,0
4,400,2,17.5,32.3,1.0,5.468232,7.611178,13,41.0,1,...,82.0,33.0,1010.8,1006.0,7.000000,8.00000,17.8,29.7,0,0

In [19]:
df_2["rain_3day"] = df_2["Rainfall"].rolling(3).sum()
df_2["rain_7day"] = df_2["Rainfall"].rolling(7).sum()
df_2["Soil_wetness_index"] = df_2['Rainfall'] - df_2['Evaporation']
df_2["Pressure_change"] = df_2["Pressure3pm"] - df_2['Pressure9am']
df_2["Humidity_change"] = df_2['Humidity3pm'] - df_2['Humidity9am']

In [20]:
# Predict Rain Intensity
X_train = df_2.drop(columns = ["Rainfall","Date","Location","WindDir9am","WindDir3pm","WindGustDir","RainToday","RainTomorrow","Temp3pm","Humidity3pm","Pressure3pm","MaxTemp"])
y_train = df_2["Rainfall"]
from xgboost import XGBRegressor
xgb_model = XGBRegressor()
xgb_model.fit(X_train,y_train)

importances = pd.Series(xgb_model.feature_importances_,index = X_train.columns)
importance = importances.sort_values(ascending = False)
importance

Soil_wetness_index    0.777352
rain_3day             0.037161
Temp9am               0.024019
Evaporation           0.020197
Cloud9am              0.019283
Cloud3pm              0.018597
Pressure9am           0.017039
Humidity_change       0.013194
WindSpeed3pm          0.011930
rain_7day             0.011341
Humidity9am           0.010511
MinTemp               0.009012
Pressure_change       0.008617
WindGustSpeed         0.008332
WindSpeed9am          0.006776
Sunshine              0.006639
dtype: float32

In [21]:
# from sklearn.model_selection import train_test_split
# from sklearn.ensemble import RandomForestRegressor
# from sklearn.metrics import mean_squared_error,r2_score
# X = df_2.drop(columns = ['Rainfall'])
# y = df_2['Rainfall']
# X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

# rg_model = RandomForestRegressor(n_estimators = 100,max_depth = None,random_state = 42)
# rg_model.fit(X_train,y_train)
# y_preds = rg_model.predict(X_test)

# mse = mean_squared_error(y_test,y_preds)
# r2 = r2_score(y_test,y_preds)

# print("MSE : ",mse)
# print("R2 Score : ",r2)

# importances = pd.Series(rg_model.feature_importances_,index = X_train.columns)
# importance = importances.sort_values(ascending = False)
# importance

In [22]:
df_2 = df_2.drop(columns = ["Date","Location","WindDir9am","WindDir3pm","WindGustDir","RainToday","RainTomorrow","Temp3pm","Humidity3pm","Pressure3pm","MaxTemp"])
df_2.columns

Index(['MinTemp', 'Rainfall', 'Evaporation', 'Sunshine', 'WindGustSpeed',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Pressure9am',
       'Cloud9am', 'Cloud3pm', 'Temp9am', 'rain_3day', 'rain_7day',
       'Soil_wetness_index', 'Pressure_change', 'Humidity_change'],
      dtype='object')